/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author ASUS
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JLabel();
        jmbPetShop = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiFuncionario = new javax.swing.JMenuItem();
        jmiAnimal = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiClienteManutencao = new javax.swing.JMenuItem();
        jmiFuncionarioManutencao = new javax.swing.JMenuItem();
        jmiAnimalManutencao = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAreaTrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wall.png"))); // NOI18N

        jmCadastro.setText("Cadastro");

        jmiCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa.png"))); // NOI18N
        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCliente);

        jmiFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcio.png"))); // NOI18N
        jmiFuncionario.setText("Funcionário");
        jmiFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiFuncionario);

        jmiAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pet.png"))); // NOI18N
        jmiAnimal.setText("Animal");
        jmiAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnimalActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiAnimal);

        jmbPetShop.add(jmCadastro);

        jmManutencao.setText("Manutenção");

        jmiClienteManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa.png"))); // NOI18N
        jmiClienteManutencao.setText("Cliente");
        jmiClienteManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteManutencaoActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiClienteManutencao);

        jmiFuncionarioManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcio.png"))); // NOI18N
        jmiFuncionarioManutencao.setText("Funcionário");
        jmiFuncionarioManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionarioManutencaoActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiFuncionarioManutencao);

        jmiAnimalManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pet.png"))); // NOI18N
        jmiAnimalManutencao.setText("Animal");
        jmiAnimalManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnimalManutencaoActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiAnimalManutencao);

        jmbPetShop.add(jmManutencao);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmbPetShop.add(jmSair);

        setJMenuBar(jmbPetShop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void abrirCadAnimal(){
        GUICadAnimal gca = new GUICadAnimal();
        jAreaTrabalho.add(gca);
        gca.setVisible(true);
    }
    
    
    
    private void abrirCadCliente(){
        GUICadCliente gcc = new GUICadCliente();
        jAreaTrabalho.add(gcc);
        gcc.setVisible(true);
    }
    
    private void abrirCadFuncionario(){
        GUICadFuncionario gcf = new GUICadFuncionario();
        jAreaTrabalho.add(gcf);
        gcf.setVisible(true);
    }
    
    private void abrirManutencaoAnimal(){
        GUIManutencaoAnimal gma = new GUIManutencaoAnimal();
        jAreaTrabalho.add(gma);
        gma.setVisible(true);
    }
    
    private void abrirManutencaoCliente(){
        GUIManutencaoCliente gmc = new GUIManutencaoCliente();
        jAreaTrabalho.add(gmc);
        gmc.setVisible(true);
    }
    
    private void abrirManutencaoFuncionario(){
        GUIManutencaoFuncionario gmf = new GUIManutencaoFuncionario();
        jAreaTrabalho.add(gmf);
        gmf.setVisible(true);
    }
    
    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        abrirCadCliente();
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnimalActionPerformed
        abrirCadAnimal();
    }//GEN-LAST:event_jmiAnimalActionPerformed

    private void jmiFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionarioActionPerformed
        abrirCadFuncionario();
    }//GEN-LAST:event_jmiFuncionarioActionPerformed

    private void jmiClienteManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteManutencaoActionPerformed
        abrirManutencaoCliente();
    }//GEN-LAST:event_jmiClienteManutencaoActionPerformed

    private void jmiAnimalManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnimalManutencaoActionPerformed
        abrirManutencaoAnimal();
    }//GEN-LAST:event_jmiAnimalManutencaoActionPerformed

    private void jmiFuncionarioManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionarioManutencaoActionPerformed
        abrirManutencaoFuncionario();
    }//GEN-LAST:event_jmiFuncionarioManutencaoActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAreaTrabalho;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuBar jmbPetShop;
    private javax.swing.JMenuItem jmiAnimal;
    private javax.swing.JMenuItem jmiAnimalManutencao;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiClienteManutencao;
    private javax.swing.JMenuItem jmiFuncionario;
    private javax.swing.JMenuItem jmiFuncionarioManutencao;
    // End of variables declaration//GEN-END:variables
}
